title: Supriya Rao Gude
logo: /Images/fotor-20240430185620.png
description: "A personal portfolio and blog by Supriya Rao Gude."
email: supriyar.gude@gmail.com
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
baseurl: ""
